services:
  db:
    image: postgres:14
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: borgertinget
      POSTGRES_PASSWORD: borgertinget123
      POSTGRES_DB: borgertinget
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: borgertinget@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: my-opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - OPENSEACH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "9200:9200"