// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250416083426_UserVoteUnique")]
    partial class UserVoteUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnswerOption", b =>
                {
                    b.Property<int>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerOptionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            AnswerOptionId = 1,
                            DisplayOrder = 1,
                            IsCorrect = true,
                            OptionText = "Studiet af magtstrukturer og beslutningsprocesser",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 2,
                            DisplayOrder = 2,
                            IsCorrect = false,
                            OptionText = "Analyse af internationale handelsaftaler",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 3,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Udforskning af historiske monarkier",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 4,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Social mobilitet",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 5,
                            DisplayOrder = 2,
                            IsCorrect = true,
                            OptionText = "Magtdeling",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 6,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Kulturel assimilation",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 7,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Planøkonomi",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 8,
                            DisplayOrder = 2,
                            IsCorrect = false,
                            OptionText = "Høj grad af omfordeling",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 9,
                            DisplayOrder = 3,
                            IsCorrect = true,
                            OptionText = "Frit marked og privat ejendomsret",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 10,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Individuel konkurrence",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerOptionId = 11,
                            DisplayOrder = 2,
                            IsCorrect = true,
                            OptionText = "Social lighed og fællesskabets velfærd",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerOptionId = 12,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Traditionelle hierarkier",
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("Flashcard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlashcardId"));

                    b.Property<int>("BackContentType")
                        .HasColumnType("integer");

                    b.Property<string>("BackImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BackText")
                        .HasColumnType("text");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("FrontContentType")
                        .HasColumnType("integer");

                    b.Property<string>("FrontImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FrontText")
                        .HasColumnType("text");

                    b.HasKey("FlashcardId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            FlashcardId = 1,
                            BackContentType = 0,
                            BackText = "Mette Frederiksen",
                            CollectionId = 1,
                            DisplayOrder = 1,
                            FrontContentType = 1,
                            FrontImagePath = "/uploads/flashcards/mettef.png"
                        },
                        new
                        {
                            FlashcardId = 2,
                            BackContentType = 0,
                            BackText = "Lars Løkke Rasmussen",
                            CollectionId = 1,
                            DisplayOrder = 2,
                            FrontContentType = 1,
                            FrontImagePath = "/uploads/flashcards/larsl.png"
                        },
                        new
                        {
                            FlashcardId = 3,
                            BackContentType = 0,
                            BackText = "Inger Støjberg",
                            CollectionId = 1,
                            DisplayOrder = 3,
                            FrontContentType = 0,
                            FrontText = "Hvem er formand for Danmarksdemokraterne?"
                        },
                        new
                        {
                            FlashcardId = 4,
                            BackContentType = 0,
                            BackText = "Folkestyre",
                            CollectionId = 2,
                            DisplayOrder = 1,
                            FrontContentType = 0,
                            FrontText = "Hvad betyder 'Demokrati'?"
                        },
                        new
                        {
                            FlashcardId = 5,
                            BackContentType = 0,
                            BackText = "Statens budget for det kommende år",
                            CollectionId = 2,
                            DisplayOrder = 2,
                            FrontContentType = 0,
                            FrontText = "Hvad er 'Finansloven'?"
                        });
                });

            modelBuilder.Entity("FlashcardCollection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectionId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("CollectionId");

                    b.ToTable("FlashcardCollections");

                    b.HasData(
                        new
                        {
                            CollectionId = 1,
                            DisplayOrder = 1,
                            Title = "Politikerne og deres navne"
                        },
                        new
                        {
                            CollectionId = 2,
                            DisplayOrder = 2,
                            Title = "Politiske begreber"
                        });
                });

            modelBuilder.Entity("Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentPageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Indhold for Politik 101...",
                            DisplayOrder = 1,
                            Title = "Politik 101"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Indhold for Den Politiske Akse...",
                            DisplayOrder = 1,
                            ParentPageId = 1,
                            Title = "Den Politiske Akse"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Indhold for Venstre vs Højre...",
                            DisplayOrder = 1,
                            ParentPageId = 2,
                            Title = "Venstre vs Højre"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Højre er at være højre...",
                            DisplayOrder = 1,
                            ParentPageId = 3,
                            Title = "Højre"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Venstre er at være venstre...",
                            DisplayOrder = 2,
                            ParentPageId = 3,
                            Title = "Venstre"
                        });
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.HasIndex("PageId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            PageId = 1,
                            QuestionText = "Hvad beskæftiger politologi sig primært med?"
                        },
                        new
                        {
                            QuestionId = 2,
                            PageId = 1,
                            QuestionText = "Hvilket begreb dækker over fordelingen af autoritet i et samfund?"
                        },
                        new
                        {
                            QuestionId = 3,
                            PageId = 4,
                            QuestionText = "Hvilket økonomisk princip forbindes ofte med højreorienteret politik?"
                        },
                        new
                        {
                            QuestionId = 4,
                            PageId = 5,
                            QuestionText = "Hvilken værdi vægtes typisk højt i venstreorienteret ideologi?"
                        });
                });

            modelBuilder.Entity("backend.Models.PoliticianTwitterId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TwitterUserId")
                        .IsUnique();

                    b.ToTable("PoliticianTwitterIds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Statsministeriet",
                            TwitterHandle = "Statsmin",
                            TwitterUserId = "806068174567460864"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Venstre, Danmarks Liberale Parti",
                            TwitterHandle = "venstredk",
                            TwitterUserId = "123868861"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Troels Lund Poulsen",
                            TwitterHandle = "troelslundp",
                            TwitterUserId = "2965907578"
                        });
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PoliticianId")
                        .HasColumnType("integer");

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PollId")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("PollOptions");
                });

            modelBuilder.Entity("backend.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianTwitterId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PoliticianTwitterId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PoliticianTwitterId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            PoliticianTwitterId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("backend.Models.Tweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<int>("Replies")
                        .HasColumnType("integer");

                    b.Property<int>("Retweets")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterTweetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianTwitterId", "TwitterTweetId")
                        .IsUnique();

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("PollId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChosenOptionId");

                    b.HasIndex("PollId");

                    b.HasIndex("UserId", "PollId")
                        .IsUnique();

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("AnswerOption", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Flashcard", b =>
                {
                    b.HasOne("FlashcardCollection", "FlashcardCollection")
                        .WithMany("Flashcards")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardCollection");
                });

            modelBuilder.Entity("Page", b =>
                {
                    b.HasOne("Page", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("Page", "Page")
                        .WithMany("AssociatedQuestions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.HasOne("backend.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("backend.Models.Subscription", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PoliticianTwitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tweet", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany("Tweets")
                        .HasForeignKey("PoliticianTwitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("backend.Models.UserVote", b =>
                {
                    b.HasOne("backend.Models.PollOption", "ChosenOption")
                        .WithMany("UserVotes")
                        .HasForeignKey("ChosenOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Poll", "Poll")
                        .WithMany("UserVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenOption");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashcardCollection", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("Page", b =>
                {
                    b.Navigation("AssociatedQuestions");

                    b.Navigation("ChildPages");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("backend.Models.PoliticianTwitterId", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Tweets");
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
