// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Aktor", b =>
                {
                    b.Property<int>("PoliticianId")
                        .HasColumnType("integer");

                    b.Property<string>("Born")
                        .HasColumnType("text");

                    b.Property<string>("Constituencies")
                        .HasColumnType("text");

                    b.Property<string>("EducationStatistic")
                        .HasColumnType("text");

                    b.Property<string>("Educations")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FunctionFormattedTitle")
                        .HasColumnType("text");

                    b.Property<string>("FunctionStartDate")
                        .HasColumnType("text");

                    b.Property<string>("MinisterTitel")
                        .HasColumnType("text");

                    b.Property<string>("Ministers")
                        .HasColumnType("text");

                    b.Property<string>("Nominations")
                        .HasColumnType("text");

                    b.Property<string>("Occupations")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ParliamentaryPositionsOfTrust")
                        .HasColumnType("text[]");

                    b.Property<string>("Party")
                        .HasColumnType("text");

                    b.Property<string>("PartyShortname")
                        .HasColumnType("text");

                    b.Property<string>("PictureMiRes")
                        .HasColumnType("text");

                    b.Property<string>("PositionsOfTrust")
                        .HasColumnType("text");

                    b.Property<string>("PublicationTitles")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Spokesmen")
                        .HasColumnType("text");

                    b.Property<string>("biografi")
                        .HasColumnType("text");

                    b.Property<string>("efternavn")
                        .HasColumnType("text");

                    b.Property<string>("fornavn")
                        .HasColumnType("text");

                    b.Property<string>("gruppeNavnKort")
                        .HasColumnType("text");

                    b.Property<string>("navn")
                        .HasColumnType("text");

                    b.Property<DateTime>("opdateringsdato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("periodeid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("slutdato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("startdato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("typeid")
                        .HasColumnType("integer");

                    b.HasKey("PoliticianId");

                    b.ToTable("Aktor");
                });

            modelBuilder.Entity("backend.Models.Calendar.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastScrapedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("StartDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.HasKey("Id");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("backend.Models.Flashcards.Flashcard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlashcardId"));

                    b.Property<int>("BackContentType")
                        .HasColumnType("integer");

                    b.Property<string>("BackImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BackText")
                        .HasColumnType("text");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("FrontContentType")
                        .HasColumnType("integer");

                    b.Property<string>("FrontImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FrontText")
                        .HasColumnType("text");

                    b.HasKey("FlashcardId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            FlashcardId = 1,
                            BackContentType = 0,
                            BackText = "Mette Frederiksen",
                            CollectionId = 1,
                            DisplayOrder = 1,
                            FrontContentType = 1,
                            FrontImagePath = "/uploads/flashcards/mettef.png"
                        },
                        new
                        {
                            FlashcardId = 2,
                            BackContentType = 0,
                            BackText = "Lars Løkke Rasmussen",
                            CollectionId = 1,
                            DisplayOrder = 2,
                            FrontContentType = 1,
                            FrontImagePath = "/uploads/flashcards/larsl.png"
                        },
                        new
                        {
                            FlashcardId = 3,
                            BackContentType = 0,
                            BackText = "Inger Støjberg",
                            CollectionId = 1,
                            DisplayOrder = 3,
                            FrontContentType = 0,
                            FrontText = "Hvem er formand for Danmarksdemokraterne?"
                        },
                        new
                        {
                            FlashcardId = 4,
                            BackContentType = 0,
                            BackText = "Folkestyre",
                            CollectionId = 2,
                            DisplayOrder = 1,
                            FrontContentType = 0,
                            FrontText = "Hvad betyder 'Demokrati'?"
                        },
                        new
                        {
                            FlashcardId = 5,
                            BackContentType = 0,
                            BackText = "Statens budget for det kommende år",
                            CollectionId = 2,
                            DisplayOrder = 2,
                            FrontContentType = 0,
                            FrontText = "Hvad er 'Finansloven'?"
                        });
                });

            modelBuilder.Entity("backend.Models.Flashcards.FlashcardCollection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectionId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("CollectionId");

                    b.ToTable("FlashcardCollections");

                    b.HasData(
                        new
                        {
                            CollectionId = 1,
                            DisplayOrder = 1,
                            Title = "Politikerne og deres navne"
                        },
                        new
                        {
                            CollectionId = 2,
                            DisplayOrder = 2,
                            Title = "Politiske begreber"
                        });
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.AnswerOption", b =>
                {
                    b.Property<int>("AnswerOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerOptionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");

                    b.HasData(
                        new
                        {
                            AnswerOptionId = 1,
                            DisplayOrder = 1,
                            IsCorrect = true,
                            OptionText = "Studiet af magtstrukturer og beslutningsprocesser",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 2,
                            DisplayOrder = 2,
                            IsCorrect = false,
                            OptionText = "Analyse af internationale handelsaftaler",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 3,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Udforskning af historiske monarkier",
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerOptionId = 4,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Social mobilitet",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 5,
                            DisplayOrder = 2,
                            IsCorrect = true,
                            OptionText = "Magtdeling",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 6,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Kulturel assimilation",
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerOptionId = 7,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Planøkonomi",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 8,
                            DisplayOrder = 2,
                            IsCorrect = false,
                            OptionText = "Høj grad af omfordeling",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 9,
                            DisplayOrder = 3,
                            IsCorrect = true,
                            OptionText = "Frit marked og privat ejendomsret",
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerOptionId = 10,
                            DisplayOrder = 1,
                            IsCorrect = false,
                            OptionText = "Individuel konkurrence",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerOptionId = 11,
                            DisplayOrder = 2,
                            IsCorrect = true,
                            OptionText = "Social lighed og fællesskabets velfærd",
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerOptionId = 12,
                            DisplayOrder = 3,
                            IsCorrect = false,
                            OptionText = "Traditionelle hierarkier",
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentPageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPageId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Indhold for Politik 101...",
                            DisplayOrder = 1,
                            Title = "Politik 101"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Indhold for Den Politiske Akse...",
                            DisplayOrder = 1,
                            ParentPageId = 1,
                            Title = "Den Politiske Akse"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Indhold for Venstre vs Højre...",
                            DisplayOrder = 1,
                            ParentPageId = 2,
                            Title = "Venstre vs Højre"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Højre er at være højre...",
                            DisplayOrder = 1,
                            ParentPageId = 3,
                            Title = "Højre"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Venstre er at være venstre...",
                            DisplayOrder = 2,
                            ParentPageId = 3,
                            Title = "Venstre"
                        });
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("PageId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.HasIndex("PageId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            PageId = 1,
                            QuestionText = "Hvad beskæftiger politologi sig primært med?"
                        },
                        new
                        {
                            QuestionId = 2,
                            PageId = 1,
                            QuestionText = "Hvilket begreb dækker over fordelingen af autoritet i et samfund?"
                        },
                        new
                        {
                            QuestionId = 3,
                            PageId = 4,
                            QuestionText = "Hvilket økonomisk princip forbindes ofte med højreorienteret politik?"
                        },
                        new
                        {
                            QuestionId = 4,
                            PageId = 5,
                            QuestionText = "Hvilken værdi vægtes typisk højt i venstreorienteret ideologi?"
                        });
                });

            modelBuilder.Entity("backend.Models.Party", b =>
                {
                    b.Property<int>("partyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("partyId"));

                    b.Property<int?>("chairmanId")
                        .HasColumnType("integer");

                    b.Property<string>("history")
                        .HasColumnType("text");

                    b.Property<string>("memberIds")
                        .HasColumnType("text");

                    b.Property<string>("partyName")
                        .HasColumnType("text");

                    b.Property<string>("partyProgram")
                        .HasColumnType("text");

                    b.Property<string>("partyShortName")
                        .HasColumnType("text");

                    b.Property<string>("politics")
                        .HasColumnType("text");

                    b.Property<int?>("secretaryId")
                        .HasColumnType("integer");

                    b.Property<int?>("spokesmanId")
                        .HasColumnType("integer");

                    b.Property<string>("stats")
                        .HasColumnType("text");

                    b.Property<int?>("viceChairmanId")
                        .HasColumnType("integer");

                    b.HasKey("partyId");

                    b.HasIndex("chairmanId");

                    b.HasIndex("secretaryId");

                    b.HasIndex("spokesmanId");

                    b.HasIndex("viceChairmanId");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("backend.Models.PoliticianTwitterId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AktorId")
                        .IsUnique();

                    b.HasIndex("TwitterUserId")
                        .IsUnique();

                    b.ToTable("PoliticianTwitterIds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Statsministeriet",
                            TwitterHandle = "Statsmin",
                            TwitterUserId = "806068174567460864"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Venstre, Danmarks Liberale Parti",
                            TwitterHandle = "venstredk",
                            TwitterUserId = "123868861"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Troels Lund Poulsen",
                            TwitterHandle = "troelslundp",
                            TwitterUserId = "2965907578"
                        });
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianTwitterId");

                    b.ToTable("Polls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            PoliticianTwitterId = 1,
                            Question = "Hvad synes du om den nye bro?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 28, 14, 30, 0, 0, DateTimeKind.Utc),
                            PoliticianTwitterId = 1,
                            Question = "Skal Danmark øge investeringer i vedvarende energi?"
                        });
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PollId")
                        .HasColumnType("integer");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("PollOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OptionText = "Den er fantastisk!",
                            PollId = 1,
                            Votes = 5
                        },
                        new
                        {
                            Id = 2,
                            OptionText = "Den er ok, men dyr.",
                            PollId = 1,
                            Votes = 12
                        },
                        new
                        {
                            Id = 3,
                            OptionText = "Den er unødvendig.",
                            PollId = 1,
                            Votes = 3
                        },
                        new
                        {
                            Id = 4,
                            OptionText = "Ja, meget mere end nu",
                            PollId = 2,
                            Votes = 42
                        },
                        new
                        {
                            Id = 5,
                            OptionText = "Ja, lidt mere",
                            PollId = 2,
                            Votes = 28
                        },
                        new
                        {
                            Id = 6,
                            OptionText = "Nej, det nuværende niveau er passende",
                            PollId = 2,
                            Votes = 15
                        },
                        new
                        {
                            Id = 7,
                            OptionText = "Nej, vi bør investere mindre",
                            PollId = 2,
                            Votes = 8
                        });
                });

            modelBuilder.Entity("backend.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianTwitterId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("backend.Models.Tweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int>("PoliticianTwitterId")
                        .HasColumnType("integer");

                    b.Property<int>("Replies")
                        .HasColumnType("integer");

                    b.Property<int>("Retweets")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterTweetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianTwitterId", "TwitterTweetId")
                        .IsUnique();

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("PollId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChosenOptionId");

                    b.HasIndex("PollId");

                    b.HasIndex("UserId", "PollId")
                        .IsUnique();

                    b.ToTable("UserVotes");
                });

            modelBuilder.Entity("backend.Models.Flashcards.Flashcard", b =>
                {
                    b.HasOne("backend.Models.Flashcards.FlashcardCollection", "FlashcardCollection")
                        .WithMany("Flashcards")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardCollection");
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.AnswerOption", b =>
                {
                    b.HasOne("backend.Models.LearningEnvironment.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Page", b =>
                {
                    b.HasOne("backend.Models.LearningEnvironment.Page", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Question", b =>
                {
                    b.HasOne("backend.Models.LearningEnvironment.Page", "Page")
                        .WithMany("AssociatedQuestions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("backend.Models.Party", b =>
                {
                    b.HasOne("backend.Models.Aktor", "chairman")
                        .WithMany()
                        .HasForeignKey("chairmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Aktor", "secretary")
                        .WithMany()
                        .HasForeignKey("secretaryId");

                    b.HasOne("backend.Models.Aktor", "spokesman")
                        .WithMany()
                        .HasForeignKey("spokesmanId");

                    b.HasOne("backend.Models.Aktor", "viceChairman")
                        .WithMany()
                        .HasForeignKey("viceChairmanId");

                    b.Navigation("chairman");

                    b.Navigation("secretary");

                    b.Navigation("spokesman");

                    b.Navigation("viceChairman");
                });

            modelBuilder.Entity("backend.Models.PoliticianTwitterId", b =>
                {
                    b.HasOne("backend.Models.Aktor", "Aktor")
                        .WithOne()
                        .HasForeignKey("backend.Models.PoliticianTwitterId", "AktorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aktor");
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany("Polls")
                        .HasForeignKey("PoliticianTwitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.HasOne("backend.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("backend.Models.Subscription", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PoliticianTwitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tweet", b =>
                {
                    b.HasOne("backend.Models.PoliticianTwitterId", "Politician")
                        .WithMany("Tweets")
                        .HasForeignKey("PoliticianTwitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("backend.Models.UserVote", b =>
                {
                    b.HasOne("backend.Models.PollOption", "ChosenOption")
                        .WithMany("UserVotes")
                        .HasForeignKey("ChosenOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Poll", "Poll")
                        .WithMany("UserVotes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenOption");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Flashcards.FlashcardCollection", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Page", b =>
                {
                    b.Navigation("AssociatedQuestions");

                    b.Navigation("ChildPages");
                });

            modelBuilder.Entity("backend.Models.LearningEnvironment.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("backend.Models.PoliticianTwitterId", b =>
                {
                    b.Navigation("Polls");

                    b.Navigation("Subscriptions");

                    b.Navigation("Tweets");
                });

            modelBuilder.Entity("backend.Models.Poll", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("backend.Models.PollOption", b =>
                {
                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
